### ISSUE TITLE
Effectiveness

### ISSUE THREAD

**Issue by suntong** [mauidude/deduper#2]
Hi Shane,

How effective is deduper?

I tried it with three simple files which contains the following string:
- "hello world foo baz bar zomg" ("id":"p1")
- "goodbye world foo qux bar zomg" ("id":"p2")
- "entirely unrelated" ("id":"p3")

then tried to add the 4th file. Here are my test results:

| 4th file content | FindSimilar threshold | Similar Found | Result Strange |
| --- | --- | --- | --- |
| hello world foo baz | 0.5 | [{"id":"p1","similarity":1}] |  |
| world foo baz | 0.5 |  | Yes |
| entirely unrelated | 0.5 | [{"id":"p3","similarity":1}] |  |
| unrelated | 0.00001 |  | Yes |
| foo qux bar zomg world goodbye | 0.5 |  | Yes |
| goodbye world foo qux bar zomg | 0.5 | [{"id":"p2","similarity":1}] |  |

Please take a look at those rows with "Result Strange" field marked as "Yes". They don't make much sense to me. Any explain? 

Thanks

**Comment by mauidude** [comment]
This is meant to be used on longer (50+ words) of text.

**Comment by suntong** [comment]
Oh, gotya. thx.
